database_common: &database_common
  database: theater
  adapter: postgresql
  encoding: utf8
  reconnect: true
  host: localhost
  username: theater_user
  password: 12345678

development:
  <<: *database_common

production:
  <<: *database_common

test:
  <<: *database_common
  database: theater_test